models:
  - name: orders_ssot
    description: "Orders data"
    # columns:
      # - name: id
      #   description: "The primary key for this table"
      #   data_tests:
      #     - unique
      #     - not_null